# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0408f8750b00d4d740c0c6cc5d027923cc835ba50254a3b16ad016e6f8acbfa059e1d5d36a83b51b12c49d4c8050a4521085e7e86a66be03169127359ec580ab

test:
  secret_key_base: a6a1f5f226e7599c31b702ac18826444152cbf04ac56c68dd91b8e3205874473bdbcdef3ee27b3b0953c8e4511f2f5cbd354d3cecf618e29f6cfb74a0c19328b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
